import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col">
        <ul className="flex w-full justify-center mb-8">
          <li className="flex-1 text-center">Home</li>
          <li className="flex-1 text-center">Experiences</li>
          <li className="flex-1 text-center">About me</li>
          <li className="flex-1 text-center">Contact</li>
        </ul>
        {children}
      </body>
    </html>
  );
}
